### ISSUE TITLE
Running the webinterface on another port

### ISSUE THREAD

**Issue by bbrala** [NoiseByNorthwest/php-spx#20]
Hi, 

I was trying to get this working on my dev env, but i can't reach the webinterface. Is there a possibility to run it on a different point so it doesn't conflict with apache?

Regards, 

Bjorn.

**Comment by NoiseByNorthwest** [comment]
Hi,

The web UI does not include a dedicated HTTP server, it is simply served by the same server which served your PHP application. 

Have you tried opening `http://localhost/_spx?SPX_KEY=dev` with the proper configuration as described [here](https://github.com/NoiseByNorthwest/php-spx#web-page) ?

**Comment by bbrala** [comment]
Hmm, yeah i tried, i can only run it from my host machine (its an vm), and apache is just serving the vhost bound. When i run it with lynx from the console i get an 404.

**Comment by NoiseByNorthwest** [comment]
You should check your client ip `var_dump($_SERVER['REMOTE_ADDR']);`  and put the right value in the configuration `spx.http_ip_whitelist="<Yout IPv4 address>"`

**Comment by bbrala** [comment]
I'll doublecheck that, since i did put my ip in the whitelist, but perhaps i made a typo. Ill get back to you.

**Comment by NoiseByNorthwest** [comment]
You may be interested by last revision of master which include some useful logs (in nginx error log or fpm error log) in case web ui access failure. See #23

**Comment by NoiseByNorthwest** [comment]
@bbrala as explained in this related issue #22 the UI root url without a trailing slash does not work. I've updated the README. You must use `http://localhost/_spx/?SPX_KEY=dev` instead.

**Comment by bbrala** [comment]
Ah cool, tomorrow i have some time to check it out again. :)

**Comment by bbrala** [comment]
Well, still not doing what it should really. I've build the current master.

Config file `/etc/php/7.0/mods-available/spx.ini`
```
[spx]
extension=spx.so
spx.http_enabled=1
spx.http_key=dev
spx.http_ip_whitelist=172.16.0.79,localhost
```
`php -i | grep spx`

```
spx.data_dir => /tmp/spx => /tmp/spx
spx.http_enabled => 1 => 1
spx.http_ip_var => REMOTE_ADDR => REMOTE_ADDR
spx.http_ip_whitelist => 172.16.0.79,localhost => 172.16.0.79,localhost
spx.http_key => dev => dev
spx.http_ui_assets_dir => /usr/share/misc/php-spx/assets/web-ui => /usr/share/misc/php-spx/assets/web-ui
spx.http_ui_uri_prefix => /_spx => /_spx
```
Apache log when trying to connect:
```
172.16.0.79 - - [15/Mar/2018:11:35:43 +0100] "GET /_spx/?SPX_KEY=dev HTTP/1.1" 404 497 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
172.16.0.79 - - [15/Mar/2018:11:35:43 +0100] "GET /_spx/?SPX_KEY=dev HTTP/1.1" 404 497 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
127.0.0.1 - - [15/Mar/2018:11:36:03 +0100] "GET /_spx/?SPX_KEY=dev HTTP/1.0" 404 458 "-" "Lynx/2.8.9dev.8 libwww-FM/2.14 SSL-MM/1.4.1 GNUTLS/3.4.9"
127.0.0.1 - - [15/Mar/2018:11:36:52 +0100] "GET /_spx/?SPX_KEY=dev HTTP/1.0" 404 458 "-" "Lynx/2.8.9dev.8 libwww-FM/2.14 SSL-MM/1.4.1 GNUTLS/3.4.9"
```

**Comment by bbrala** [comment]
And th elocation of spx.ini. (apache has been restarted also)

```
$ locate spx.ini
/etc/php/7.0/apache2/conf.d/20-spx.ini
/etc/php/7.0/cli/conf.d/20-spx.ini
```

**Comment by bbrala** [comment]
Hmm, could it be Apache is just not supported? :x

**Comment by NoiseByNorthwest** [comment]
Yes it is possible. I'll try with apache2 this evening.

**Comment by NoiseByNorthwest** [comment]
@bbrala I've an issue with apache2 / mod_php 7.0, web UI HTTP responses are ill-formed (see below). I'll fix it in a few days.

```
HTTP/1.1 200 OK
Date: Thu, 15 Mar 2018 21:51:52 GMT
Server: Apache/2.4.7 (Ubuntu)
Transfer-Encoding: chunked

HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 12245

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>SPX Control Panel</title>
        <script>
        (() => {
...
```

**Comment by bbrala** [comment]
Thanks :)

**Comment by cmizzi** [comment]
I've got same result on `apache2 / mod_php-5.6`

**Comment by NoiseByNorthwest** [comment]
@bbrala @cmizzi You should try last master revision. It should be ok since merge of #34.

**Comment by bbrala** [comment]
I tried again in master, unfortunately, it is still nog working. Commandline is fine, but through apache still gives an 404.

**Comment by cmizzi** [comment]
Hum, it's look like to work for my configuration (`apache2 / mod_php5.6` through `nginx`)

```dockerfile
RUN set -xe \
    && cd /tmp \
    && git clone https://github.com/NoiseByNorthwest/php-spx.git \
    && cd php-spx \
    && phpize \
    && ./configure \
    && make \
    && make install \
    && echo "spx.http_enabled=1\nspx.http_key=\"dev\"\nspx.http_ip_whitelist=\"127.0.0.1,172.123.0.200\"\nspx.http_ui_assets_dir=/usr/share/misc/php-spx/assets/web-ui\nextension=spx.so" > /etc/php5/mods-available/spx.ini \
    && php5enmod spx
```

**Comment by cmizzi** [comment]
But, for projects working on Laravel, I've got a 301 loop redirections

```http
HTTP/1.1 301 Moved Permanently
Server: nginx/1.12.2
Date: Mon, 19 Mar 2018 09:41:03 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Location: /_spx/?SPX_KEY=dev
Vary: Accept-Encoding
```

```http
HTTP/1.1 301 Moved Permanently
Server: nginx/1.12.2
Date: Mon, 19 Mar 2018 09:42:07 GMT
Content-Type: text/html; charset=iso-8859-1
Connection: keep-alive
Location: http://xxx/_spx?SPX_KEY=dev
Vary: Accept-Encoding
```
The first tries to append the ending `/` and the second removes it

**Comment by NoiseByNorthwest** [comment]
@cmizzi OK I just see the .htaccess used by Laravel https://github.com/laravel/laravel/blob/master/public/.htaccess#L12

Is `localhost/_spx/index.html?SPX_KEY=dev` OK for you ? If so I will make /_spx redirecting to /_spx/index.html

**Comment by NoiseByNorthwest** [comment]
@bbrala Can you provide SPX notice logs ? (those starting with "SPX: access")
Can you also try (and give me the output with headers) the following urls ?
`localhost/_spx?SPX_KEY=dev`
`localhost/_spx/?SPX_KEY=dev`
`localhost/_spx/index.html?SPX_KEY=dev`

**Comment by cmizzi** [comment]
@NoiseByNorthwest This seems to work. I would be great to redirect on it, I don't think I'm not only with this problem. I didn't try directly in `apache` configuration but it should works IMO

**Comment by NoiseByNorthwest** [comment]
@cmizzi done on master (redirection to .../index.html)

**Comment by bbrala** [comment]
What do you mean with the SPX notice logs?

**Comment by NoiseByNorthwest** [comment]
This kind of log `PHP Notice:  SPX: access granted: "172.123.0.200" IP with "dev" key in Unknown on line 0` Please see @cmizzi comment above for a full example. BTW you need to set `log_errors=1` in apache2's php.ini

I do not reproduce the apache2 bugs since merge of #34. So you have to help me by trying the urls listed in my previous and giving me back the response headers & spx notice logs.
